### ISSUE TITLE
Error: Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by sunying12** [yguoma/GEM3#11]
Hi, I am running gem with the S.irio genome with this command 

java -Xmx10G -jar Read_Distribution_default.txt --s genome size readdistribution.txt --genome genome --expt $file.sam --f SAM --k_min 6 --k_max 20 --k_seqs 600 --k_neg_dinu_shuffle --t $threads --outNP

**and got this error:** 

Exception in thread "main" java.lang.NullPointerException
	at edu.mit.csail.cgs.deepseq.utilities.AlignmentFileReader.populateArrays(AlignmentFileReader.java:260)
	at edu.mit.csail.cgs.deepseq.utilities.SAMReader.countReads(SAMReader.java:86)
	at edu.mit.csail.cgs.deepseq.utilities.AlignmentFileReader.getTotalHits(AlignmentFileReader.java:310)
	at edu.mit.csail.cgs.deepseq.utilities.FileReadLoader.<init>(FileReadLoader.java:147)
	at edu.mit.csail.cgs.deepseq.DeepSeqExpt.<init>(DeepSeqExpt.java:84)
	at edu.mit.csail.cgs.deepseq.DeepSeqExpt.<init>(DeepSeqExpt.java:78)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.<init>(GEM.java:126)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:343)

the Si_genome.chrom.size.txt looks like this: 

lcl|chrSI_scaffold1     72289
lcl|chrSI_scaffold2     42255
lcl|chrSI_scaffold3     19911
lcl|chrSI_scaffold4     116093
lcl|chrSI_scaffold5     264581...

Please help! Thanks!

**Comment by yguoma** [comment]
Try adding a --g option.
http://groups.csail.mit.edu/cgs/gem/#examples
--g [path] The path to a genome information file (genome.chrom.sizes file)
<http://groups.csail.mit.edu/cgs/gem/versions.html>. The file contains
tab-delimited chromosome name/length pairs. Highly recommended, although
not required. If it is not supplied, GEM will use the maximum value of read
coordinate as the chomosome length.

**Comment by sunying12** [comment]
Hi Yunchun,

Thanks for your email! I believe --g is the same as --genome which I
already have. I think the issue may be that GEM only runs when chr is at
the start of every "chromosome" but for scaffolds and contigs they don't
always start with chr and I normally have to rename them.

What do you think? Thanks!

- Ying
- Ying Sun
PhD Candidate
Stanford Biology
sunyings@stanford.edu
