### ISSUE TITLE
error running GEM

### ISSUE THREAD

**Issue by Sunnysum** [yguoma/GEM3#12]
Hi, I am running gem with the S.irio genome with this command
java -Xmx10G -jar gem.jar --d Read_Distribution_default.txt --g mm8.chrom.sizes --genome /home/scc/software/biosoft/data/bowtie2/hg19.idx --s 2000000000 --expt /home/liusiyu/S1.sam --ctrl /home/liusiyu/input.sam --f SAM --out /home/liusiyu/S1_GEM --k_min 6 --k_max 13 
and got this error:
java.io.FileNotFoundException: GEM_Log.txt (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:82)
	at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.<init>(KPPMixture.java:146)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.<init>(GEM.java:146)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:343)

Options:
--d Read_Distribution_default.txt --g mm8.chrom.sizes --genome /home/scc/software/biosoft/data/bowtie2/hg19.idx --s 2000000000 --expt /home/liusiyu/S1.sam --ctrl /home/liusiyu/input.sam --f SAM --out /home/liusiyu/S1_GEM --k_min 6 --k_max 13 
java.lang.NullPointerException
	at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.log(KPPMixture.java:3661)
	at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.<init>(KPPMixture.java:197)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.<init>(GEM.java:146)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:343)
Exception in thread "main" java.lang.NullPointerException
	at edu.mit.csail.cgs.deepseq.discovery.GEM.runMixtureModel(GEM.java:166)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:345)
Please help! Thanks!

**Comment by yguoma** [comment]
Are you running this on mm8 or hg19? Make sure that the --g, --genome, and
your read alignment data are consistent.
