### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: for ChIP-nexus/ChIP-exo BAM file

### ISSUE THREAD

**Issue by khyatiCK** [yguoma/GEM3#21]
Hi, 
  
 I am trying to run the following command on the ChIP-nexus/ChIP-exo BAM file. 
 java -jar -Xmx400G ~/bin/gem/gem.jar --expt nexus_filtered_combined.bam  --d ~/bin/gem/Read_Distribution_ChIP-exo.txt 
--g ~/bin/gem/mm10.chrom.sizes --f SAM --out test --outNP --mrc 150

I get the following error:
Exception in thread "main" java.lang.NullPointerException
	at edu.mit.csail.cgs.deepseq.utilities.AlignmentFileReader.populateArrays(AlignmentFileReader.java:260)
	at edu.mit.csail.cgs.deepseq.utilities.SAMReader.countReads(SAMReader.java:86)
	at edu.mit.csail.cgs.deepseq.utilities.AlignmentFileReader.getTotalHits(AlignmentFileReader.java:310)
	at edu.mit.csail.cgs.deepseq.utilities.FileReadLoader.<init>(FileReadLoader.java:147)
	at edu.mit.csail.cgs.deepseq.DeepSeqExpt.<init>(DeepSeqExpt.java:84)
	at edu.mit.csail.cgs.deepseq.DeepSeqExpt.<init>(DeepSeqExpt.java:78)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.<init>(GEM.java:126)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:343)

I used --mrc 150 because we have our pipeline to remove duplicates.

What is it that I may be doing wrong?

**Comment by yguoma** [comment]
The SAM/BAM file loading code might not be up-to-date with the newer alignment tools. I would recommend converting them to BED file first.
