### ISSUE TITLE
Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by bliu36** [yguoma/GEM3#26]
Hi,
I am running GEM with my chip-exo data and my organism is Candida glabrata.

The code I was using is: 
java -Xmx10G -jar gem.jar --d Read_Distribution_ChIP-exo.txt --smooth 3 --g cglabrata.chrom.sizes --genome /projects/academic/lrusche/chip_exocg/GCA_014217725.1_ASM1421772v1_genomic.fna --s 12300000 --expt Hst1_1.bed --ctrl No_tag.bed --f BED --out gem_Hst1_1 --nrf --outBED --k_min 6 --k_max 13

However, I got this error:
Exception in thread "main" java.lang.NullPointerException
	at edu.mit.csail.cgs.deepseq.utilities.AlignmentFileReader.populateArrays(AlignmentFileReader.java:260)
	at edu.mit.csail.cgs.deepseq.utilities.BEDFileReader.countReads(BEDFileReader.java:124)
	at edu.mit.csail.cgs.deepseq.utilities.AlignmentFileReader.getTotalHits(AlignmentFileReader.java:310)
	at edu.mit.csail.cgs.deepseq.utilities.FileReadLoader.<init>(FileReadLoader.java:147)
	at edu.mit.csail.cgs.deepseq.DeepSeqExpt.<init>(DeepSeqExpt.java:84)
	at edu.mit.csail.cgs.deepseq.DeepSeqExpt.<init>(DeepSeqExpt.java:78)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.<init>(GEM.java:126)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:343)

Could you please tell me how to fix it? Thank you!

**Comment by yguoma** [comment]
Please share first 5 lines for the following files:
cglabrata.chrom.sizes
Hst1_1.bed
No_tag.bed

Also, have you successfully run GEM for other dataset?

**Comment by bliu36** [comment]
Hi, 
Thanks for the response! No, I haven't managed to run GEM with any dataset yet. And I was actually trying to run GEM with BAM file and I read some previous questions on the same error then decided to use bed file (which was generated by bedtools). I am sharing the first 5 lines of all these files as following:
**cglabrata.chrom.sizes:**
chrA	527800
chrB	512655
chrC	594526
chrD	667900 
chrE	707423
**Hst1_1.bed:**
CP048230.1	23	52	AV234001:988-989:2141911342:2:21302:0838:3156/1	7	+
CP048230.1	23	51	AV234001:988-989:2141911342:2:11603:4296:0464/2	60	+
CP048230.1	23	52	AV234001:988-989:2141911342:2:21302:0838:3156/2	15	-
CP048230.1	23	51	AV234001:988-989:2141911342:2:11603:4296:0464/1	60	-
CP048230.1	24	43	AV234001:988-989:2141911342:2:10501:0592:3502/1	40	+
**No_tag.bed:**
CP048230.1	167	224	AV234001:988-989:2141911342:2:11003:1801:0045/2	0	+
CP048230.1	168	237	AV234001:988-989:2141911342:2:21902:4817:2999/1	17	+
CP048230.1	169	218	AV234001:988-989:2141911342:2:20202:5181:3207/1	0	+
CP048230.1	169	218	AV234001:988-989:2141911342:2:10505:0085:1703/1	0	+
CP048230.1	169	239	AV234001:988-989:2141911342:2:12103:1046:3305/2	0	+

**Comment by yguoma** [comment]
The chromosome column (CP048230.1) in your bed files should match the ones (chrA, chrB, ...) in the chrome.size file.

**Comment by bliu36** [comment]
Hi, I actually fixed the chromosome name issue but it still gives me the same error messages.

**Comment by bliu36** [comment]
I also tried to create  smaller versions of my BED files with only the first few lines but have the same errors.

**Comment by yguoma** [comment]
Please show the 5 lines of all three files again.

**Comment by bliu36** [comment]
**cglabrata.chrom.sizes:**
CP048230.1	527800
CP048231.1	512655
CP048232.1	594526
CP048233.1	667900
CP048234.1	707423
**Hst1_1.bed:**
CP048230.1 23 52 AV234001:988-989:2141911342:2:21302:0838:3156/1 7 +
CP048230.1 23 51 AV234001:988-989:2141911342:2:11603:4296:0464/2 60 +
CP048230.1 23 52 AV234001:988-989:2141911342:2:21302:0838:3156/2 15 -
CP048230.1 23 51 AV234001:988-989:2141911342:2:11603:4296:0464/1 60 -
CP048230.1 24 43 AV234001:988-989:2141911342:2:10501:0592:3502/1 40 +
**No_tag.bed:**
CP048230.1 167 224 AV234001:988-989:2141911342:2:11003:1801:0045/2 0 +
CP048230.1 168 237 AV234001:988-989:2141911342:2:21902:4817:2999/1 17 +
CP048230.1 169 218 AV234001:988-989:2141911342:2:20202:5181:3207/1 0 +
CP048230.1 169 218 AV234001:988-989:2141911342:2:10505:0085:1703/1 0 +
CP048230.1 169 239 AV234001:988-989:2141911342:2:12103:1046:3305/2 0 +

**Comment by yguoma** [comment]
I'd suggest first run GEM with the test files on the GEM website: http://groups.csail.mit.edu/cgs/gem/#examples

Also, just to double check, you should use TAB as delimiter for these file.

**Comment by bliu36** [comment]
I have tried to run the test files and they worked fine. Could you further explain "use as delimiter"? 
Also, before I get the error, this was shown: Loading data...Loading reads from: Hst1_1.bed ... Loaded
Does that mean my bed file is okay? Can I run the program without ctrl? If my bed file is okay, where is the issue from?
Thank you!

**Comment by yguoma** [comment]
I meant "use TAB, not SPACE, as delimiter". Somehow it was removed by GitHub when posted.

Yes, you can run it without the ctrl data.
