### ISSUE TITLE
Error running GEM

### ISSUE THREAD

**Issue by JMFZ** [yguoma/GEM3#8]
Hello,
After running several GEM jobs I received the following error and stops running:

IP: 16932832    Ctrl: 16296675   IP/Ctrl: 1,04

Sorting reads and selecting enriched regions ...
java.lang.ArrayIndexOutOfBoundsException: -1
        at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.calcSlope(KPPMixture.java:3078)
        at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.getSlope(KPPMixture.java:3057)
        at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.calcIpCtrlRatio(KPPMixture.java:1995)
        at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.<init>(KPPMixture.java:360)
        at edu.mit.csail.cgs.deepseq.discovery.GEM.<init>(GEM.java:146)
        at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:343)
Exception in thread "main" java.lang.NullPointerException
        at edu.mit.csail.cgs.deepseq.discovery.GEM.runMixtureModel(GEM.java:166)
        at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:345)

I must say that I got this error while running with two particular BAMs but not with some other BAMs using the same command, since with the latter I got nice data.
I’d appreciate any advice. 
Regards,

**Comment by yguoma** [comment]
Please post your command line arguments for running GEM with the error
datasets. You might also want to convert them into BED files first, and
then run GEM.

Best,

Yuchun

**Comment by JMFZ** [comment]
Thank you for your comments. Following you suggestions, I converted my BAMs into BED and got the same error. I guess there is no a problem with my command line since the same arguments don't give any error with some other BAMs.

My command line is:

java -Xmx4G -jar gem.jar --d Read_Distribution_default.txt --g TAIR10-genome_sizes.txt --genome ./AthGenome/ --s 120000000 --expt myBAMexp.bam  --ctrl myBAMcont.bam --out myBAM-GEM --f BED --outNP --range 150 --smooth 4 --mrc 1 --fold 2 --q 1.301029996  --k_min 6 --k_max 20 --k_seqs 600 --k_neg_dinu_shuffle --pp_nmotifs 3 

Many thanks for your interest
Best,

Jose
